site_name: Overwatch Team Comp Tool
site_description: Projekt documentation for the SQS project
repo_url: https://github.com/FabianReinelt-stud/OverwatchTeamUp
edit_uri: edit/main/docs/

theme:
  name: material
  language: en

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Setup: setup.md
  - Test Concept: testconcept.md
  - API DTOs: api-dtos.md
  - Architecture:
      - arc42: architecture/arc42.md
      - C4-Modell: architecture/c4-model.md
  - ADRs:
      - ADR-01 Python & Django: adr/adr-01-python-django.md
      - ADR-02 React & TypeScript: adr/adr-02-react-typescript.md
      - ADR-03 Hexagonal Architecture: adr/adr-03-hexagonal-architecture.md
      - ADR-04 PostgreSQL: adr/adr-04-postgresql.md
      - Template: adr/template.md
