sonar.projectKey=FabianReinelt-stud_OverwatchTeamUp
sonar.organization=fabianreinelt-stud
sonar.sources=backend/app
sonar.tests=backend/app
sonar.exclusions=**/tests.py,**/test_*.py,**/*_test.py,**/migrations/**,**/fixtures/**,**/__pycache__/**
sonar.test.inclusions=**/tests.py,**/test_*.py,**/*_test.py
sonar.coverage.exclusions=**/tests.py,**/test_*.py,**/*_test.py,**/migrations/**,**/manage.py
sonar.python.coverage.reportPaths=backend/app/coverage.xml
