sonar.projectKey=FabianReinelt-stud_OverwatchTeamUp
sonar.organization=fabianreinelt-stud
sonar.sources=backend/app,frontend/src
sonar.tests=backend/app,frontend/src,frontend/e2e
sonar.exclusions=**/tests.py,**/test_*.py,**/*_test.py,**/migrations/**,**/fixtures/**,**/__pycache__/**,**/architecture_tests/**,frontend/src/assets/**,frontend/src/fonts/**,frontend/src/data/api-dtos.tsx
sonar.test.inclusions=**/tests.py,**/test_*.py,**/*_test.py,frontend/src/**/*.test.tsx,frontend/e2e/**/*.ts
sonar.coverage.exclusions=**/tests.py,**/test_*.py,**/*_test.py,**/migrations/**,**/manage.py,**/architecture_tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,frontend/src/main.tsx,frontend/src/data/**,frontend/e2e/**
sonar.python.coverage.reportPaths=backend/app/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
