# Generated by Django 6.0.5 on 2026-05-14 09:08

#from django.db import migrations, models


#class Migration(migrations.Migration):

#    initial = True

#    dependencies = [
#    ]

#    operations = [
#        migrations.CreateModel(
#            name='Hero',
#            fields=[
#                ('hero_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
#                ('display_name', models.CharField(max_length=30)),
#                ('role', models.CharField(max_length=30)),
#                ('subrole', models.CharField(max_length=30)),
#                ('winrate', models.DecimalField(decimal_places=1, max_digits=4)),
#                ('pickrate', models.DecimalField(decimal_places=1, max_digits=4)),
#                ('health', models.IntegerField()),
#                ('armor', models.IntegerField()),
#                ('shields', models.IntegerField()),
#                ('portrait_url', models.TextField()),
#                ('description', models.TextField()),
#            ],
#            options={
#                'db_table': 'hero',
#            },
#        ),
#    ]
