# Generated by Django 6.0.5 on 2026-05-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_comp_hero_1', to='heroes.hero')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_comp_hero_2', to='heroes.hero')),
                ('hero_3', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_comp_hero_3', to='heroes.hero')),
                ('hero_4', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_comp_hero_4', to='heroes.hero')),
                ('hero_5', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_comp_hero_5', to='heroes.hero')),
            ],
            options={
                'db_table': 'team_comps',
            },
        ),
    ]
