# Generated by Django 6.0.5 on 2026-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_teamcomposition_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
    ]
